name: sharath_property
description: Sharath Property Management App.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.1
  url_launcher: ^6.1.14
  pull_to_refresh: ^2.0.0
  flutter_config: ^2.0.0
  font_awesome_flutter: ^10.5.0
  basic_utils: ^5.6.1
  intl:
  carousel_slider: ^4.2.1
  expandable: ^5.0.1
  expandable_text: ^2.3.0
  lottie: ^2.6.0
  photo_view: ^0.14.0
  pod_player: ^0.2.1
  intl_phone_field: ^3.2.0
  loader_overlay: ^2.3.0
  flutter_styled_toast: ^2.1.3
  flutter_rating_bar: ^4.0.1
  timeago: ^3.5.0
  store_redirect: ^2.0.1
  flutter_share: ^2.0.0
  list_tile_switch:
  image_picker: ^1.0.4
  flutter_offline: ^3.0.0
  syncfusion_flutter_sliders: ^20.4.44
  google_maps_flutter: ^2.4.0
  onesignal_flutter: ^3.4.1
  flutter_local_notifications: ^15.1.1
  # device_info_plus: ^9.1.0

  device_uuid: ^0.0.4
  
  # platform_device_id:
  #   path: z_packages/platform_device_id-1.0.1
  system_settings:
    path: z_packages/system_settings-2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0


flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  image_path: "assets/launcher/app_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/launcher/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/launcher/
    - assets/near_by/
    - assets/types/

  fonts:
    - family: Fredoka-SemiBold
      fonts:
        - asset: assets/fonts/Fredoka-SemiBold.ttf
    - family: Fredoka-Medium
      fonts:
        - asset: assets/fonts/Fredoka-Medium.ttf
    - family: SFUIDisplay-Bold
      fonts:
        - asset: assets/fonts/SFUIDisplay-Bold.ttf
    - family: Montserrat-Black
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
   
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: Montserrat-ExtraLight
      fonts:
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
    - family: Montserrat-Light
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
    - family: Montserrat-Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Montserrat-SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: Montserrat-Thin
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf